import { createClient } from "../../../lib/supabase-server"
import GrandFormatLayout from "../../../components/GrandFormatLayout";
import DetteClient from "./DetteClient";

export const metadata = {
  title: "L'État insolvable, Soara",
  description: "La dette publique mondiale a franchi 100 000 milliards de dollars. Ce n'est pas la dette qui inquiète. C'est ce qu'elle révèle.",
};

export default async function Page({ searchParams }: { searchParams?: { lang?: string } }) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  const isAdmin = user?.email === 'steve.moradel@gmail.com'
  let isSubscribed = false
  if (user && !isAdmin) {
    const { data: profile } = await supabase.from('profiles').select('subscription_status').eq('id', user.id).single()
    isSubscribed = profile?.subscription_status === 'active' || profile?.subscription_status === 'trialing'
  }
  const showPaywall = !isAdmin && !isSubscribed
  const lang = searchParams?.lang === 'en' ? 'en' : 'fr'

  return (
    <GrandFormatLayout slug="dette-souveraine" author="Steve Moradel" authorRole=""
      lang={lang}
      hasEnglish={true}>
      <div style={{ margin:"0 -40px 48px", borderTop:"1.5px solid #DDD9D2", borderBottom:"1.5px solid #DDD9D2" }}>
        <DetteClient />
      </div>
      <div className="soara-article">
        <p><strong>Cent mille milliards de dollars.</strong> Prenons un instant pour mesurer ce que ce chiffre représente. Pas une projection catastrophiste, pas un scénario dystopique forgé par des économistes alarmistes. La dette publique mondiale a franchi ce seuil. Elle dépasse désormais 95&nbsp;% du PIB mondial. Ce n'est pas la dette qui inquiète. Ce que la dette révèle, voilà le vrai sujet&nbsp;: des sociétés qui ont systématiquement préféré emprunter au futur plutôt que de trancher dans le présent. La facture arrive. Pas sous forme de krach spectaculaire. Sous celle, bien plus sourde, d'un État qui rétrécit, qui renonce à éduquer ses enfants, à soigner ses malades, à défendre ses frontières. La dette publique n'est pas un problème de comptabilité nationale. C'est un révélateur anthropologique.</p>
        <p>Cinq pays concentrent à eux seuls près de 70&nbsp;% de cette masse&nbsp;: les États-Unis, la Chine, le Japon, la France et l'Italie. Leurs trajectoires divergent. Leur diagnostic commun est le même&nbsp;: la dette n'est plus chez eux un instrument de politique publique. Elle est devenue la contrainte qui s'est substituée à la politique.</p>

        <h2>L'empire qui travaille pour <em>ses créanciers</em></h2>
        <p><strong>Les États-Unis ont vécu pendant un demi-siècle sous le régime de ce que Valéry Giscard d'Estaing appelait le "privilège exorbitant".</strong> Emprunter dans sa propre monnaie, dans un monde qui a érigé le dollar en actif de réserve universel. Ce privilège se fissure. En 2025, les paiements d'intérêts ont dépassé 1&nbsp;100 milliards de dollars, devenant le premier poste de dépenses fédérales, devant la défense, devant Medicare. Quand le service de la dette devient le premier poste budgétaire d'un empire, c'est que l'empire travaille pour ses créanciers. Il n'est plus vraiment souverain au sens plein du terme.</p>
        <p><strong>La Chine présente le cas le plus opaque du classement.</strong> Sa dette officielle, 77&nbsp;% du PIB — paraît raisonnable. Mais une fois intégrées les dettes des collectivités locales, dissimulées dans des véhicules de financement hors bilan, le chiffre réel dépasse probablement 110 à 130&nbsp;% du PIB. La crise de l'immobilier depuis 2021, avec l'effondrement d'Evergrande, a mis à nu cette fragilité. La gestion autoritaire de la dette évite la panique à court terme, mais elle empêche le signal de prix qui forcerait les ajustements nécessaires.</p>
        <p><strong>Le Japon est l'anomalie statistique</strong> qui fascine les économistes depuis trente ans. À 230&nbsp;% du PIB, pas de crise de confiance. 90&nbsp;% de la dette est détenue par des résidents. Mais le vieillissement accéléré signifie que les épargnants d'aujourd'hui deviendront les désépargnants de demain. Le Japon prouve qu'une dette à 230&nbsp;% du PIB n'est pas automatiquement létale. Il ne prouve pas qu'elle est indéfiniment soutenable.</p>
        <p><strong>La France incarne une contradiction douloureuse.</strong> Elle a construit l'un des systèmes de protection sociale les plus généreux au monde. Et elle ne peut plus le financer sans s'endetter davantage. En cinq ans, les intérêts ont doublé&nbsp;: de 52,9 milliards d'euros en 2023 à 60,2 milliards en 2024. Près d'un titre de dette sur deux est dans les mains d'investisseurs non résidents.</p>
        <p><strong>L'Italie est le malade chronique</strong> de la zone euro, avec 137&nbsp;% du PIB depuis un quart de siècle. Ce n'est plus une crise, c'est un état permanent. Ensemble, France et Italie représentent près de la moitié de la dette publique totale de la zone euro.</p>

        <h2>Ce que la dette <em>empêche</em></h2>
        <p>La charge annuelle de la dette française est comparable au budget entier de l'Éducation nationale, 63 milliards d'euros. Argent qui ne forme personne. Argent qui ne construit rien. Cette éviction se mesure dans le classement de Shanghai, dans l'exode des chercheurs vers Londres, Boston, Singapour. Quand un État doit choisir entre payer ses intérêts et former sa jeunesse, il choisit ses intérêts. Les marchés financiers n'attendent pas. Les enfants des banlieues, eux, peuvent attendre.</p>
        <p>Ce que la dette empêche ne figure dans aucun bilan officiel. Il s'agit d'un manque&nbsp;: les hôpitaux qu'on n'a pas construits, les réseaux ferrés qu'on n'a pas rénovés, les laboratoires de recherche publique qu'on n'a pas financés. La dette ne détruit pas seulement de la richesse présente, elle ampute la capacité à en produire dans le futur. C'est ce que les économistes appellent l'effet d'éviction&nbsp;: chaque euro consacré au service de la dette est un euro soustrait à l'investissement productif. La France, en 2025, consacre à ses créanciers une somme supérieure à ce qu'elle dépense pour la transition énergétique, la défense ou l'enseignement supérieur pris séparément.</p>
        <div className="pull-quote"><p>En 2025, le poids des intérêts de la dette française dépassait celui du budget de la Défense nationale. Une puissance nucléaire, membre permanent du Conseil de sécurité, consacre plus d'argent à rémunérer ses créanciers qu'à financer sa propre sécurité militaire.</p></div>
        <p>Il existe aussi une géographie de la contrainte. Les pays du Sud global ont longtemps porté seuls le regard condescendant des institutions de Bretton Woods sur leur gestion financière. Les plans d'ajustement structurel imposés par le FMI au Ghana, à l'Argentine ou à la Zambie ont fait l'objet d'analyses critiques exhaustives. Mais la dynamique qui frappe aujourd'hui les économies avancées n'est pas fondamentalement différente&nbsp;: c'est la même logique de la dette qui se substitue à la politique, le même rétrécissement de l'espace démocratique sous la pression des marchés. La différence, c'est que personne ne l'appelle ajustement structurel.</p>

        <h2>L'angle mort&nbsp;: <em>ce qu'on choisit de ne pas percevoir</em></h2>
        <p>Chaque année, entre 80 et 100 milliards d'euros s'évaporent des caisses publiques françaises à travers l'évasion fiscale. C'est plus que la totalité de l'impôt sur le revenu. Pendant ce temps, la Direction Générale des Finances Publiques a perdu près de 34&nbsp;000 équivalents temps plein depuis 2008. On réduit les gendarmes fiscaux tout en se plaignant que les caisses sont vides. L'évasion fiscale et la dette publique sont les deux faces d'un même transfert&nbsp;: l'une des formes les plus élaborées de socialisation des pertes et de privatisation des gains.</p>
        <p>Il existe une autre catégorie d'angles morts&nbsp;: les dépenses fiscales. En France, elles représentent plus de 80 milliards d'euros annuels, niches, crédits d'impôt, exonérations dont l'efficacité économique n'a jamais été véritablement évaluée. Elles s'accumulent par sédimentation législative, chaque gouvernement ajoutant les siennes sans supprimer les précédentes. C'est de la dépense publique déguisée en manque à gagner fiscal. Et comme elle n'apparaît pas dans le budget, personne ne vote pour la supprimer. Le débat public s'épuise à discuter d'ajustements à la marge, quelques centaines de millions ici ou là, tandis que des dizaines de milliards dorment, intouchables, dans des dispositifs que leurs bénéficiaires ont appris à rendre invisibles.</p>
        <p>La critique la plus sérieuse que l'on puisse adresser à la gestion de la dette française n'est pas technique. Elle est politique. Les instruments existent. Les leviers sont connus. Ce qui manque, c'est la volonté de les activer contre des intérêts organisés qui ont appris à neutraliser toute tentative de réforme. En ce sens, la dette n'est pas le symptôme d'une incompétence collective. Elle est le produit d'un rapport de forces.</p>

        <h2>Une question de <em>souveraineté</em></h2>
        <p>Une nation qui ne peut financer ses choix qu'à condition que des acteurs extérieurs lui prêtent les ressources nécessaires n'est plus tout à fait souveraine. Elle est sous tutelle. Douce, invisible, mais réelle. De Gaulle l'avait compris avant tout le monde&nbsp;: <em>«&nbsp;Nous ne pouvons avoir une politique indépendante et une défense indépendante, si nous n'avons pas une économie indépendante et des finances saines.&nbsp;»</em> Cinquante-cinq ans après sa mort, l'endettement public français a été multiplié par huit.</p>
        <p>La souveraineté budgétaire n'est pas qu'une abstraction comptable. Elle détermine le périmètre réel de la décision politique. Quand les taux d'intérêt remontent de 100 points de base, la France dépense mécaniquement plusieurs milliards supplémentaires en service de la dette, sans qu'aucun gouvernement, aucun parlement, aucun citoyen n'ait eu à se prononcer. La décision appartient à la BCE, aux marchés obligataires, aux agences de notation. Ce sont des institutions non élues qui fixent, en partie, le cadre dans lequel s'exerce la démocratie française. Ce renversement de légitimité mérite d'être nommé clairement&nbsp;: il s'agit bien d'une forme de dépossession, consentie par accumulation de déficits successifs.</p>
        <p>Les pays émergents qui ont traversé des crises de dette souveraine, l'Argentine en 2001, la Grèce en 2010, ont vécu cette réalité de façon brutale&nbsp;: l'État contraint de négocier avec ses créanciers la nature même de sa politique sociale, salariale, éducative. La France n'en est pas là. Mais la direction empruntée depuis quarante ans pointe dans ce sens. Le débat démocratique ne devrait pas seulement porter sur la réduction du déficit. Il devrait porter sur ce que l'accumulation de dette transfère, progressivement et silencieusement, hors du champ de la décision collective.</p>

        <h2>La dette <em>invisible</em></h2>
        <p>Il existe une dette dont on ne parle presque jamais. En France, si l'on cumule la dette publique nette et les engagements hors bilan, dont les seules retraites des fonctionnaires représentent 1&nbsp;800 milliards d'euros, on dépasse les 7&nbsp;000 milliards d'euros. Soit plus du double de la dette comptable officielle. En 2025, pour la première fois depuis la fin de la Seconde Guerre mondiale, le solde naturel de la population française est devenu négatif. Il y a quelque chose d'intellectuellement malhonnête dans un débat public qui agite les 3&nbsp;460 milliards de dette officielle tout en ignorant les engagements hors bilan qui en représentent le double.</p>

        <h2>Un choix, <em>pas une fatalité</em></h2>
        <p><strong>La dette publique est un choix.</strong> L'accumulation, sur cinq décennies, de choix validés démocratiquement, qui ont tous opté pour la même solution&nbsp;: consommer aujourd'hui des ressources qui appartiennent à demain. Ce n'est pas de la corruption. C'est de la rationalité politique à courte vue. Aucun gouvernement n'a jamais gagné une élection en promettant la rigueur.</p>
        <p>Des trajectoires alternatives ont pourtant existé. La Suède, au début des années 1990, a fait face à une crise financière et budgétaire d'une sévérité comparable à celle de la Grèce en 2010. Elle a choisi l'ajustement, douloureux, rapide, conduit avec un large consensus politique et syndical. En moins d'une décennie, elle avait transformé un déficit de 12&nbsp;% du PIB en excédent budgétaire. Elle dispose aujourd'hui de l'une des finances publiques les plus solides d'Europe. Ce n'est pas un miracle nordique. C'est le résultat d'un choix de société, délibéré et assumé.</p>
        <p>La comparaison ne vise pas à plaider pour l'austérité indifférenciée. Elle vise à démontrer que la contrainte budgétaire n'est pas une loi naturelle, c'est le résidu de décisions accumulées. Et que d'autres décisions sont possibles, à condition de ne pas confondre l'inévitable et le confortable. La question n'est plus de savoir si la France devra ajuster ses finances publiques. Elle est de savoir si cet ajustement se fera dans le cadre d'un projet politique choisi, ou sous la pression de marchés que personne n'aura su anticiper.</p>
        <div className="pull-quote"><p>La souveraineté de demain se construit dans les budgets d'aujourd'hui. Si nous continuons à différer, ce ne sont pas les marchés qui nous prendront notre liberté. C'est nous-mêmes qui l'aurons hypothéquée.</p></div>
      </div>
    </GrandFormatLayout>
  );
}
