export type Solution = {
  name: string
  cat: Category
  rawCat: string
  country: string
  iso: string
  website: string
  image?: string
  credit?: string
}

export type Category =
  | 'Eau' | 'Énergie' | 'Biodiversité' | 'Agriculture' | 'Économie circulaire'
  | 'Océans' | 'Santé' | 'Inclusion' | 'Mobilité' | 'Matériaux'
  | "Finance d'impact" | 'Climat' | 'Sciences & Tech'

export type CountryInfo = {
  fr: string
  iso: string
  lng: number
  lat: number
}

export const COUNTRY_INFO: Record<string, CountryInfo> = {
  'Australia':          { fr: 'Australie',           iso: 'AUS', lng: 133.77, lat: -25.27 },
  'Belgium':            { fr: 'Belgique',            iso: 'BEL', lng: 4.47,   lat: 50.5   },
  'Cameroon':           { fr: 'Cameroun',            iso: 'CMR', lng: 12.35,  lat: 5.37   },
  'Canada':             { fr: 'Canada',              iso: 'CAN', lng: -96.8,  lat: 56.13  },
  'Denmark':            { fr: 'Danemark',            iso: 'DNK', lng: 9.5,    lat: 56.26  },
  'Dominican Republic': { fr: 'République dominicaine', iso: 'DOM', lng: -70.16, lat: 18.74 },
  'Egypt':              { fr: 'Égypte',              iso: 'EGY', lng: 30.80,  lat: 26.82  },
  'Finland':            { fr: 'Finlande',            iso: 'FIN', lng: 25.74,  lat: 61.92  },
  'France':             { fr: 'France',              iso: 'FRA', lng: 2.35,   lat: 46.85  },
  'Germany':            { fr: 'Allemagne',           iso: 'DEU', lng: 10.45,  lat: 51.17  },
  'Ghana':              { fr: 'Ghana',               iso: 'GHA', lng: -1.02,  lat: 7.95   },
  'India':              { fr: 'Inde',                iso: 'IND', lng: 78.96,  lat: 20.59  },
  'Israel':             { fr: 'Israël',              iso: 'ISR', lng: 34.85,  lat: 31.05  },
  'Italy':              { fr: 'Italie',              iso: 'ITA', lng: 12.57,  lat: 41.87  },
  'Japan':              { fr: 'Japon',               iso: 'JPN', lng: 138.25, lat: 36.2   },
  'Kenya':              { fr: 'Kenya',               iso: 'KEN', lng: 37.91,  lat: 0.02   },
  'Luxembourg':         { fr: 'Luxembourg',          iso: 'LUX', lng: 6.13,   lat: 49.61  },
  'Mauritania':         { fr: 'Mauritanie',          iso: 'MRT', lng: -10.94, lat: 21.0   },
  'Morocco':            { fr: 'Maroc',               iso: 'MAR', lng: -7.09,  lat: 31.79  },
  'Netherlands':        { fr: 'Pays-Bas',            iso: 'NLD', lng: 5.29,   lat: 52.13  },
  'Nigeria':            { fr: 'Nigeria',             iso: 'NGA', lng: 8.67,   lat: 9.08   },
  'Norway':             { fr: 'Norvège',             iso: 'NOR', lng: 8.47,   lat: 60.47  },
  'Poland':             { fr: 'Pologne',             iso: 'POL', lng: 19.15,  lat: 51.92  },
  'Rwanda':             { fr: 'Rwanda',              iso: 'RWA', lng: 29.87,  lat: -1.94  },
  'Saudi Arabia':       { fr: 'Arabie saoudite',     iso: 'SAU', lng: 45.08,  lat: 23.89  },
  'Singapore':          { fr: 'Singapour',           iso: 'SGP', lng: 103.82, lat: 1.35   },
  'Slovenia':           { fr: 'Slovénie',            iso: 'SVN', lng: 14.99,  lat: 46.15  },
  'South Africa':       { fr: 'Afrique du Sud',      iso: 'ZAF', lng: 22.94,  lat: -30.56 },
  'South Korea':        { fr: 'Corée du Sud',        iso: 'KOR', lng: 127.77, lat: 35.91  },
  'Spain':              { fr: 'Espagne',             iso: 'ESP', lng: -3.75,  lat: 40.46  },
  'Sweden':             { fr: 'Suède',               iso: 'SWE', lng: 18.64,  lat: 60.13  },
  'Switzerland':        { fr: 'Suisse',              iso: 'CHE', lng: 8.23,   lat: 46.82  },
  'Ukraine':            { fr: 'Ukraine',             iso: 'UKR', lng: 31.16,  lat: 48.38  },
  'United Kingdom':     { fr: 'Royaume-Uni',         iso: 'GBR', lng: -1.17,  lat: 52.36  },
  'United States':      { fr: 'États-Unis',          iso: 'USA', lng: -98.58, lat: 39.83  },
}

export const CATEGORIES: { key: Category; emoji: string; color: string; bg: string }[] = [
  { key: 'Eau',                 emoji: '◐', color: '#1A4A7A', bg: '#EEF3FB' },
  { key: 'Énergie',             emoji: '◑', color: '#B86A1A', bg: '#FDF5EE' },
  { key: 'Biodiversité',        emoji: '◒', color: '#2A5A2A', bg: '#F0F7F0' },
  { key: 'Agriculture',         emoji: '◓', color: '#6B4A1A', bg: '#FAF3EE' },
  { key: 'Économie circulaire', emoji: '◔', color: '#1A3E6B', bg: '#EEF3FA' },
  { key: 'Océans',              emoji: '◕', color: '#0D3A6B', bg: '#EEF2FA' },
  { key: 'Santé',               emoji: '○', color: '#7A1A2A', bg: '#FAEEF0' },
  { key: 'Inclusion',           emoji: '◖', color: '#5A1A5A', bg: '#F7EEF7' },
  { key: 'Mobilité',            emoji: '◗', color: '#1A3A5A', bg: '#EEF2FA' },
  { key: 'Matériaux',           emoji: '◘', color: '#5A3A2A', bg: '#F7F3F0' },
  { key: "Finance d'impact",    emoji: '◙', color: '#1A3A5A', bg: '#EEF2F7' },
  { key: 'Climat',              emoji: '◚', color: '#1A4A5A', bg: '#EEF5F5' },
  { key: 'Sciences & Tech',     emoji: '◛', color: '#4A2080', bg: '#F3EEF7' },
]

const C = (k: Category) => k

export const solutions: Solution[] = [
  { name: 'Coast 4C',                                    cat: C('Océans'),              rawCat: 'Ocean / Water',                country: 'Australia',          iso: 'AUS', website: 'https://www.coast4c.com/' },
  { name: 'Syrinx Environmental',                        cat: C('Eau'),                 rawCat: 'Water / Nature-based',          country: 'Australia',          iso: 'AUS', website: 'https://www.syrinx.net.au' },
  { name: 'Avecom',                                      cat: C('Eau'),                 rawCat: 'Wastewater / Water Tech',       country: 'Belgium',            iso: 'BEL', website: 'https://www.avecom.be' },
  { name: 'BeeOdiversity',                               cat: C('Biodiversité'),        rawCat: 'Biodiversity',                  country: 'Belgium',            iso: 'BEL', website: 'https://beeodiversity.com' },
  { name: 'Citronics',                                   cat: C('Économie circulaire'), rawCat: 'Circularity / Materials',       country: 'Belgium',            iso: 'BEL', website: 'https://citronics.eu/' },
  { name: 'Euclid Network',                              cat: C('Inclusion'),           rawCat: 'Social Enterprise Network',     country: 'Belgium',            iso: 'BEL', website: 'https://www.euclidnetwork.eu' },
  { name: 'Fanyatu',                                     cat: C('Biodiversité'),        rawCat: 'Biodiversity',                  country: 'Belgium',            iso: 'BEL', website: 'https://fanyatu.org/' },
  { name: 'Smart Cities Marketplace',                    cat: C('Mobilité'),            rawCat: 'Smart Cities',                  country: 'Belgium',            iso: 'BEL', website: 'https://smart-cities-marketplace.ec.europa.eu' },
  { name: 'Urban Forests',                               cat: C('Biodiversité'),        rawCat: 'Nature / Biodiversity',         country: 'Belgium',            iso: 'BEL', website: 'https://www.urbanforest.be/en/home-4/' },
  { name: 'ClinicHome',                                  cat: C('Santé'),               rawCat: 'Health',                        country: 'Cameroon',           iso: 'CMR', website: 'https://www.clinichome.cm/' },
  { name: 'Ukuzola',                                     cat: C('Inclusion'),           rawCat: 'Education / Entrepreneurship',  country: 'Cameroon',           iso: 'CMR', website: 'https://www.ukuzola.org/' },
  { name: 'Wandusoa',                                    cat: C('Agriculture'),         rawCat: 'Agri / Food',                   country: 'Cameroon',           iso: 'CMR', website: 'https://wandusoa.org/' },
  { name: 'e-Zinc',                                      cat: C('Énergie'),             rawCat: 'Energy Storage',                country: 'Canada',             iso: 'CAN', website: 'https://www.e-zinc.ca' },
  { name: 'Oneka Technologies',                          cat: C('Eau'),                 rawCat: 'Water',                         country: 'Canada',             iso: 'CAN', website: 'https://www.onekatech.com' },
  { name: 'Lapee',                                       cat: C('Eau'),                 rawCat: 'Sanitation',                    country: 'Denmark',            iso: 'DNK', website: 'https://lapee.com' },
  { name: 'REFUNITE',                                    cat: C('Inclusion'),           rawCat: 'Inclusion / Refugees',          country: 'Denmark',            iso: 'DNK', website: 'https://refu.nite.org' },
  { name: 'SOS Biotech',                                 cat: C('Océans'),              rawCat: 'Ocean / Water',                 country: 'Dominican Republic', iso: 'DOM', website: 'https://sosbiotech.co/' },
  { name: 'BioEnergy',                                   cat: C('Énergie'),             rawCat: 'Circular Economy / Energy',     country: 'Egypt',              iso: 'EGY', website: 'https://www.bioenergyegy.com/' },
  { name: 'Resistomap',                                  cat: C('Eau'),                 rawCat: 'Water / Monitoring',            country: 'Finland',            iso: 'FIN', website: 'https://resistomap.com' },
  { name: 'Agronnect',                                   cat: C('Agriculture'),         rawCat: 'AgriTech',                      country: 'France',             iso: 'FRA', website: 'https://agronnect.fr' },
  { name: 'Amaya',                                       cat: C('Inclusion'),           rawCat: 'Social Impact',                 country: 'France',             iso: 'FRA', website: 'https://www.amaya.earth' },
  { name: 'Aquaphys',                                    cat: C('Eau'),                 rawCat: 'Water / IoT',                   country: 'France',             iso: 'FRA', website: 'https://aquaphys.com' },
  { name: 'Asteria',                                     cat: C('Climat'),              rawCat: 'Climate / AI',                  country: 'France',             iso: 'FRA', website: 'https://asteria.observer' },
  { name: 'BioeSol',                                     cat: C('Énergie'),             rawCat: 'Energy',                        country: 'France',             iso: 'FRA', website: 'https://www.bioesol.fr' },
  { name: 'Biomede',                                     cat: C('Agriculture'),         rawCat: 'AgriTech',                      country: 'France',             iso: 'FRA', website: 'https://www.biomede.fr' },
  { name: 'CECACAO',                                     cat: C('Agriculture'),         rawCat: 'Food / Agriculture',            country: 'France',             iso: 'FRA', website: 'https://www.cecacao.com' },
  { name: 'CHITELIX',                                    cat: C('Matériaux'),           rawCat: 'Circular Biomaterials',         country: 'France',             iso: 'FRA', website: 'https://chitelix.com' },
  { name: 'Etendart',                                    cat: C('Économie circulaire'), rawCat: 'Circularity',                   country: 'France',             iso: 'FRA', website: 'https://etendart.com' },
  { name: 'FabBRICK',                                    cat: C('Matériaux'),           rawCat: 'Circular Materials',            country: 'France',             iso: 'FRA', website: 'https://fab-brick.com' },
  { name: 'Fair Play For Planet',                        cat: C('Climat'),              rawCat: 'Sport / Impact',                country: 'France',             iso: 'FRA', website: 'https://fairplayforplanet.org' },
  { name: 'Finemind',                                    cat: C('Inclusion'),           rawCat: 'EdTech / Inclusion',            country: 'France',             iso: 'FRA', website: 'https://www.finemind.co' },
  { name: 'Gaiago',                                      cat: C('Agriculture'),         rawCat: 'AgriTech',                      country: 'France',             iso: 'FRA', website: 'https://www.gaiago.eu' },
  { name: 'Green Sanctuaries',                           cat: C('Biodiversité'),        rawCat: 'Biodiversity',                  country: 'France',             iso: 'FRA', website: 'https://greensanctuaries.com' },
  { name: 'HelioRec',                                    cat: C('Énergie'),             rawCat: 'Energy',                        country: 'France',             iso: 'FRA', website: 'https://www.heliorec.com' },
  { name: 'Heliosand',                                   cat: C('Eau'),                 rawCat: 'Water / Desalination',          country: 'France',             iso: 'FRA', website: 'https://www.heliosand.com' },
  { name: 'Hylight',                                     cat: C('Climat'),              rawCat: 'Climate / Methane Detection',   country: 'France',             iso: 'FRA', website: 'https://www.hylight.tech' },
  { name: 'InovaYa',                                     cat: C('Eau'),                 rawCat: 'Water',                         country: 'France',             iso: 'FRA', website: 'https://inovaya.com' },
  { name: 'Intersektion',                                cat: C('Inclusion'),           rawCat: 'Urban / Inclusion',             country: 'France',             iso: 'FRA', website: 'https://intersektion.co' },
  { name: 'Kinomé',                                      cat: C('Biodiversité'),        rawCat: 'Nature-based Solutions',        country: 'France',             iso: 'FRA', website: 'https://kinome.fr' },
  { name: 'Neolithe',                                    cat: C('Économie circulaire'), rawCat: 'Circular / Waste',              country: 'France',             iso: 'FRA', website: 'https://neolithe.fr' },
  { name: 'Novobiom',                                    cat: C('Sciences & Tech'),     rawCat: 'Biotech',                       country: 'France',             iso: 'FRA', website: 'https://novobiom.com' },
  { name: 'Peel Lab',                                    cat: C('Matériaux'),           rawCat: 'Materials',                     country: 'France',             iso: 'FRA', website: 'https://www.peel-lab.com' },
  { name: 'Rebond',                                      cat: C('Économie circulaire'), rawCat: 'Circularity',                   country: 'France',             iso: 'FRA', website: 'https://www.rebond.co' },
  { name: 'Revolty',                                     cat: C('Énergie'),             rawCat: 'Energy Storage',                country: 'France',             iso: 'FRA', website: 'https://www.revolty.fr' },
  { name: 'SolReed',                                     cat: C('Énergie'),             rawCat: 'Solar / Circularity',           country: 'France',             iso: 'FRA', website: 'https://www.cea.fr/english/Pages/solreed.aspx' },
  { name: 'Solicaz',                                     cat: C('Énergie'),             rawCat: 'Energy',                        country: 'France',             iso: 'FRA', website: 'https://solicaz.com' },
  { name: 'Synovance',                                   cat: C('Sciences & Tech'),     rawCat: 'Biotech',                       country: 'France',             iso: 'FRA', website: 'https://synovance.com' },
  { name: 'The Ocean Package',                           cat: C('Océans'),              rawCat: 'Ocean / Circularity',           country: 'France',             iso: 'FRA', website: 'https://www.theoceanpackage.com' },
  { name: 'Toore',                                       cat: C('Économie circulaire'), rawCat: 'Circularity Software',          country: 'France',             iso: 'FRA', website: 'https://toore.co' },
  { name: 'Trizzy',                                      cat: C('Économie circulaire'), rawCat: 'Zero Waste',                    country: 'France',             iso: 'FRA', website: 'https://trizzy.io' },
  { name: 'Yuka',                                        cat: C('Santé'),               rawCat: 'Health / Consumer',             country: 'France',             iso: 'FRA', website: 'https://yuka.io' },
  { name: 'CataCycle',                                   cat: C('Économie circulaire'), rawCat: 'Circularity / PET',             country: 'Germany',            iso: 'DEU', website: 'https://catacycle.com' },
  { name: 'FASE',                                        cat: C("Finance d'impact"),    rawCat: 'Impact Finance',                country: 'Germany',            iso: 'DEU', website: 'https://www.fa-se.de' },
  { name: 'FINDS',                                       cat: C('Économie circulaire'), rawCat: 'Circularity / Retail Tech',     country: 'Germany',            iso: 'DEU', website: 'https://www.getfinds.co' },
  { name: 'Klim',                                        cat: C('Agriculture'),         rawCat: 'Regenerative Agriculture',      country: 'Germany',            iso: 'DEU', website: 'https://klim.eco' },
  { name: 'Koralo',                                      cat: C('Agriculture'),         rawCat: 'FoodTech',                      country: 'Germany',            iso: 'DEU', website: 'https://koralo.com' },
  { name: 'Planet Wild',                                 cat: C('Biodiversité'),        rawCat: 'Nature / Biodiversity',         country: 'Germany',            iso: 'DEU', website: 'https://planetwild.com/' },
  { name: 'Plastic Fischer',                             cat: C('Économie circulaire'), rawCat: 'Circularity / Waste',           country: 'Germany',            iso: 'DEU', website: 'https://plasticfischer.com' },
  { name: 'Solaq',                                       cat: C('Énergie'),             rawCat: 'Energy',                        country: 'Germany',            iso: 'DEU', website: 'https://www.solaq.energy' },
  { name: 'African Fashion Foundation',                  cat: C('Inclusion'),           rawCat: 'Fashion / Ecosystem',           country: 'Ghana',              iso: 'GHA', website: 'https://africanfashionfoundation.org/' },
  { name: 'Green Africa Youth Organization',             cat: C('Climat'),              rawCat: 'Climate / Ecosystem',           country: 'Ghana',              iso: 'GHA', website: 'https://www.greenafricayouth.org/' },
  { name: 'Skin Gourmet',                                cat: C('Économie circulaire'), rawCat: 'Sustainable Beauty',            country: 'Ghana',              iso: 'GHA', website: 'https://skingourmet.com' },
  { name: 'Baeru',                                       cat: C('Océans'),              rawCat: 'Ocean / Water',                 country: 'India',              iso: 'IND', website: 'https://baeru.in/' },
  { name: 'Serein',                                      cat: C('Santé'),               rawCat: 'Health / Sustainability',       country: 'India',              iso: 'IND', website: 'https://www.serein.in' },
  { name: 'Soilytix',                                    cat: C('Agriculture'),         rawCat: 'AgriTech',                      country: 'Israel',             iso: 'ISR', website: 'https://www.soilytix.com' },
  { name: 'betterSoil',                                  cat: C('Agriculture'),         rawCat: 'AgriTech',                      country: 'Israel',             iso: 'ISR', website: 'https://bettersoil.co' },
  { name: 'WSense',                                      cat: C('Océans'),              rawCat: 'Ocean / Water',                 country: 'Italy',              iso: 'ITA', website: 'https://wsense.it/' },
  { name: 'Fermenstation',                               cat: C('Économie circulaire'), rawCat: 'Circularity / Materials',       country: 'Japan',              iso: 'JPN', website: 'https://fermenstation.co.jp/' },
  { name: 'FarmBizAfrica',                               cat: C('Agriculture'),         rawCat: 'AgriTech / Carbon',             country: 'Kenya',              iso: 'KEN', website: 'https://www.farmbizafrica.com' },
  { name: 'MAASH',                                       cat: C('Agriculture'),         rawCat: 'Food / Agri',                   country: 'Kenya',              iso: 'KEN', website: 'https://maashfoods.com' },
  { name: 'Mukuru Clean Stoves',                         cat: C('Énergie'),             rawCat: 'Energy',                        country: 'Kenya',              iso: 'KEN', website: 'https://mukurustoves.org/' },
  { name: 'Reality Academy',                             cat: C('Inclusion'),           rawCat: 'Education / Skills',            country: 'Kenya',              iso: 'KEN', website: 'https://realityacademy.co' },
  { name: 'Small Farm Cities Africa',                    cat: C('Agriculture'),         rawCat: 'Food / Agriculture',            country: 'Kenya',              iso: 'KEN', website: 'https://smallfarmcitiesafrica.com' },
  { name: 'Nash FintechX',                               cat: C("Finance d'impact"),    rawCat: 'Climate FinTech',               country: 'Luxembourg',         iso: 'LUX', website: 'https://www.nashfintechx.com' },
  { name: 'RSS-Hydro',                                   cat: C('Eau'),                 rawCat: 'Hydrology / Earth Observation', country: 'Luxembourg',         iso: 'LUX', website: 'https://www.rss-hydro.lu' },
  { name: 'Pan-African Agency of the Great Green Wall',  cat: C('Biodiversité'),        rawCat: 'Biodiversity / Land',           country: 'Mauritania',         iso: 'MRT', website: 'https://grandemurailleverte.org' },
  { name: 'ToumAI',                                      cat: C('Sciences & Tech'),     rawCat: 'AI for Impact',                 country: 'Morocco',            iso: 'MAR', website: 'https://toum.ai/' },
  { name: 'Altamira',                                    cat: C("Finance d'impact"),    rawCat: 'Regenerative Finance',          country: 'Netherlands',        iso: 'NLD', website: 'https://www.altamira-regen.com' },
  { name: 'Antfarm',                                     cat: C('Économie circulaire'), rawCat: 'Circularity',                   country: 'Netherlands',        iso: 'NLD', website: 'https://antfarm.co' },
  { name: 'ChemReclaim',                                 cat: C('Économie circulaire'), rawCat: 'Circularity / Chemicals',       country: 'Netherlands',        iso: 'NLD', website: 'https://chemreclaim.com' },
  { name: 'Coding the Curbs',                            cat: C('Mobilité'),            rawCat: 'Mobility / Smart City',         country: 'Netherlands',        iso: 'NLD', website: 'https://codingthecurbs.com' },
  { name: 'DRK Foundation',                              cat: C("Finance d'impact"),    rawCat: 'Venture Philanthropy',          country: 'Netherlands',        iso: 'NLD', website: 'https://www.drkfoundation.nl' },
  { name: 'EcoVerum',                                    cat: C('Agriculture'),         rawCat: 'AgriTech',                      country: 'Netherlands',        iso: 'NLD', website: 'https://ecoverum.nl' },
  { name: 'Goodwell Investments',                        cat: C("Finance d'impact"),    rawCat: 'Impact Investing',              country: 'Netherlands',        iso: 'NLD', website: 'https://www.goodwell.nl' },
  { name: 'Hydraloop',                                   cat: C('Eau'),                 rawCat: 'Water',                         country: 'Netherlands',        iso: 'NLD', website: 'https://www.hydraloop.com' },
  { name: 'InspireXChange',                              cat: C("Finance d'impact"),    rawCat: 'Startup Accelerator',           country: 'Netherlands',        iso: 'NLD', website: 'https://inspirexchange.nl' },
  { name: 'Justdiggit',                                  cat: C('Biodiversité'),        rawCat: 'Biodiversity',                  country: 'Netherlands',        iso: 'NLD', website: 'https://justdiggit.org' },
  { name: 'KICO Kitchen',                                cat: C('Agriculture'),         rawCat: 'Agri / Food Innovation',        country: 'Netherlands',        iso: 'NLD', website: 'https://www.kico.kitchen/' },
  { name: 'Kelp Blue',                                   cat: C('Océans'),              rawCat: 'Ocean / Water',                 country: 'Netherlands',        iso: 'NLD', website: 'https://www.kelp.blue/global' },
  { name: 'Life Terra Foundation',                       cat: C('Biodiversité'),        rawCat: 'Nature / Biodiversity',         country: 'Netherlands',        iso: 'NLD', website: 'https://www.lifeterra.eu/en' },
  { name: 'Mudland',                                     cat: C('Matériaux'),           rawCat: 'Nature-based / Materials',      country: 'Netherlands',        iso: 'NLD', website: 'https://mudland.eco' },
  { name: 'Mutual Empathy',                              cat: C("Finance d'impact"),    rawCat: 'Impact Venture Studio',         country: 'Netherlands',        iso: 'NLD', website: 'https://www.mutualempathy.com' },
  { name: 'MycoFarming',                                 cat: C('Agriculture'),         rawCat: 'AgriTech',                      country: 'Netherlands',        iso: 'NLD', website: 'https://www.mycofarming.com' },
  { name: 'NOWOS',                                       cat: C('Économie circulaire'), rawCat: 'Circularity / Batteries',       country: 'Netherlands',        iso: 'NLD', website: 'https://nowos.world' },
  { name: 'Netherlands Advisory Board on Impact Investing', cat: C("Finance d'impact"), rawCat: 'Impact Investing',              country: 'Netherlands',        iso: 'NLD', website: 'https://www.nabimpactinvesting.nl' },
  { name: 'North Sea Farmers',                           cat: C('Océans'),              rawCat: 'Ocean / Agriculture',           country: 'Netherlands',        iso: 'NLD', website: 'https://www.northseafarmers.org' },
  { name: 'Pretty Plastic',                              cat: C('Économie circulaire'), rawCat: 'Circularity',                   country: 'Netherlands',        iso: 'NLD', website: 'https://www.prettyplastic.nl' },
  { name: 'Rabo Foundation',                             cat: C("Finance d'impact"),    rawCat: 'Agri-finance / Inclusion',      country: 'Netherlands',        iso: 'NLD', website: 'https://www.rabobank.com/about-us/rabo-foundation' },
  { name: 'Roetz Bikes',                                 cat: C('Mobilité'),            rawCat: 'Mobility',                      country: 'Netherlands',        iso: 'NLD', website: 'https://roetz.life' },
  { name: 'SeaO2',                                       cat: C('Océans'),              rawCat: 'Ocean / Carbon Removal',        country: 'Netherlands',        iso: 'NLD', website: 'https://www.seao2.com' },
  { name: 'Sensiblue',                                   cat: C('Eau'),                 rawCat: 'Water',                         country: 'Netherlands',        iso: 'NLD', website: 'https://sensiblue.com' },
  { name: 'Shaping Impact Group',                        cat: C("Finance d'impact"),    rawCat: 'Impact Investing',              country: 'Netherlands',        iso: 'NLD', website: 'https://www.shapingimpact.group' },
  { name: 'Skilledin Green',                             cat: C('Inclusion'),           rawCat: 'Green Jobs / Talent',           country: 'Netherlands',        iso: 'NLD', website: 'https://green.skilledin.io' },
  { name: 'Social Impact Fonds Den Haag',                cat: C("Finance d'impact"),    rawCat: 'Impact Investing',              country: 'Netherlands',        iso: 'NLD', website: 'https://www.sifdenhaag.nl' },
  { name: 'Space4Good',                                  cat: C('Climat'),              rawCat: 'Space / Climate Data',          country: 'Netherlands',        iso: 'NLD', website: 'https://space4good.com' },
  { name: 'Swarmed',                                     cat: C('Biodiversité'),        rawCat: 'Biodiversity / Pollinators',    country: 'Netherlands',        iso: 'NLD', website: 'https://www.beeswarmed.org' },
  { name: 'Teens Safe Space',                            cat: C('Inclusion'),           rawCat: 'Inclusion',                     country: 'Netherlands',        iso: 'NLD', website: 'https://teenssafespace.com' },
  { name: 'The Great Bubble Barrier',                    cat: C('Eau'),                 rawCat: 'Water',                         country: 'Netherlands',        iso: 'NLD', website: 'https://thegreatbubblebarrier.com' },
  { name: 'The Hague Humanity Hub',                      cat: C('Inclusion'),           rawCat: 'Peace / Justice Ecosystem',     country: 'Netherlands',        iso: 'NLD', website: 'https://www.humanityhub.net' },
  { name: 'The Roots',                                   cat: C('Inclusion'),           rawCat: 'Social Design / Tech for Good', country: 'Netherlands',        iso: 'NLD', website: 'https://www.theroots.space' },
  { name: 'WellDecommissioned',                          cat: C('Énergie'),             rawCat: 'Energy',                        country: 'Netherlands',        iso: 'NLD', website: 'https://welldecommissioned.com' },
  { name: "World's Youth for Climate Justice",           cat: C('Climat'),              rawCat: 'Climate Justice',               country: 'Netherlands',        iso: 'NLD', website: 'https://www.wy4cj.org' },
  { name: 'Yespers',                                     cat: C('Agriculture'),         rawCat: 'Food / Agriculture',            country: 'Netherlands',        iso: 'NLD', website: 'https://yespers.com' },
  { name: 'i-did',                                       cat: C('Économie circulaire'), rawCat: 'Circularity',                   country: 'Netherlands',        iso: 'NLD', website: 'https://i-did.nl' },
  { name: 'leafy.',                                      cat: C('Économie circulaire'), rawCat: 'Circularity',                   country: 'Netherlands',        iso: 'NLD', website: 'https://leafy.place' },
  { name: 'Haima Health Initiative',                     cat: C('Santé'),               rawCat: 'Health',                        country: 'Nigeria',            iso: 'NGA', website: 'https://haimahealth.org.ng/' },
  { name: 'Over Easy Solar',                             cat: C('Énergie'),             rawCat: 'Solar',                         country: 'Norway',             iso: 'NOR', website: 'https://www.overeasy.no' },
  { name: 'ETV',                                         cat: C('Énergie'),             rawCat: 'Clean Tech / Wind',             country: 'Poland',             iso: 'POL', website: 'https://etvwind.com' },
  { name: 'Alliance for Healthy Communities',            cat: C('Santé'),               rawCat: 'Health',                        country: 'Rwanda',             iso: 'RWA', website: 'https://www.ahcglobal.org/' },
  { name: 'REDO',                                        cat: C('Agriculture'),         rawCat: 'Land & Agriculture',            country: 'Rwanda',             iso: 'RWA', website: 'https://redo.org.rw/' },
  { name: 'Darah Solutions Lab',                         cat: C('Économie circulaire'), rawCat: 'Textile Circularity',           country: 'Saudi Arabia',       iso: 'SAU', website: 'https://prezi.com/p/zbn-85hkklc7/darah-solutions-lab/' },
  { name: 'Flint',                                       cat: C('Énergie'),             rawCat: 'Energy Storage',                country: 'Singapore',          iso: 'SGP', website: 'https://flintbattery.com' },
  { name: 'PlanetCare',                                  cat: C('Économie circulaire'), rawCat: 'Circular / Microplastics',      country: 'Slovenia',           iso: 'SVN', website: 'https://planetcare.org' },
  { name: 'Living Soils',                                cat: C('Agriculture'),         rawCat: 'Regenerative Agriculture',      country: 'South Africa',       iso: 'ZAF', website: 'https://livingsoils.co.za' },
  { name: 'Code of Nature',                              cat: C('Biodiversité'),        rawCat: 'Nature / Biodiversity',         country: 'South Korea',        iso: 'KOR', website: 'https://www.c-of-n.com/en' },
  { name: 'Strong by Form',                              cat: C('Matériaux'),           rawCat: 'Materials',                     country: 'Spain',              iso: 'ESP', website: 'https://strongbyform.com' },
  { name: 'NitroCapt',                                   cat: C('Agriculture'),         rawCat: 'AgriTech / Fertilizer',         country: 'Sweden',             iso: 'SWE', website: 'https://nitrocapt.com' },
  { name: 'AgroSustain',                                 cat: C('Agriculture'),         rawCat: 'AgriTech',                      country: 'Switzerland',        iso: 'CHE', website: 'https://www.agrosustain.ch' },
  { name: 'Flamingo',                                    cat: C('Biodiversité'),        rawCat: 'Biodiversity / Wetlands',       country: 'Switzerland',        iso: 'CHE', website: 'https://flamingo.eco/' },
  { name: 'HERA Digital Health',                         cat: C('Santé'),               rawCat: 'HealthTech',                    country: 'Switzerland',        iso: 'CHE', website: 'https://hera-health.com' },
  { name: 'ID Genève',                                   cat: C('Économie circulaire'), rawCat: 'Sustainable Luxury',            country: 'Switzerland',        iso: 'CHE', website: 'https://www.idgenevewatches.com' },
  { name: 'NatureRe',                                    cat: C('Biodiversité'),        rawCat: 'Nature / Biodiversity / Carbon', country: 'Switzerland',       iso: 'CHE', website: 'https://nature-re.com/' },
  { name: 'Solskin',                                     cat: C('Matériaux'),           rawCat: 'Built Environment',             country: 'Switzerland',        iso: 'CHE', website: 'https://solskin.ch' },
  { name: 'Voltiris',                                    cat: C('Énergie'),             rawCat: 'Energy / Agri',                 country: 'Switzerland',        iso: 'CHE', website: 'https://www.voltiris.com' },
  { name: 'Apixmed',                                     cat: C('Santé'),               rawCat: 'HealthTech',                    country: 'Ukraine',            iso: 'UKR', website: 'https://apixmed.com' },
  { name: 'Autistic People Friendly',                    cat: C('Inclusion'),           rawCat: 'Inclusion / Autism',            country: 'Ukraine',            iso: 'UKR', website: 'https://autisticpeoplefriendly.com' },
  { name: "Felmar's Lab",                                cat: C('Santé'),               rawCat: 'HealthTech',                    country: 'Ukraine',            iso: 'UKR', website: 'https://felmars.com' },
  { name: 'Go To-U',                                     cat: C('Mobilité'),            rawCat: 'Mobility / EV',                 country: 'Ukraine',            iso: 'UKR', website: 'https://go-tou.com' },
  { name: 'Hydratico',                                   cat: C('Eau'),                 rawCat: 'Water',                         country: 'Ukraine',            iso: 'UKR', website: 'https://hydratico.com' },
  { name: 'Recast Plastic',                              cat: C('Économie circulaire'), rawCat: 'Circularity',                   country: 'Ukraine',            iso: 'UKR', website: 'https://recastplastic.com' },
  { name: 'Recup Green',                                 cat: C('Économie circulaire'), rawCat: 'Circularity / Waste',           country: 'Ukraine',            iso: 'UKR', website: 'https://recup-green.com/' },
  { name: 'S.Lab',                                       cat: C('Matériaux'),           rawCat: 'Materials',                     country: 'Ukraine',            iso: 'UKR', website: 'https://slab.com.ua' },
  { name: 'Swapp',                                       cat: C('Économie circulaire'), rawCat: 'Secondhand Fashion',            country: 'Ukraine',            iso: 'UKR', website: 'https://swappapp.io' },
  { name: 'Wood Mood',                                   cat: C('Matériaux'),           rawCat: 'Sustainable Home Decor',        country: 'Ukraine',            iso: 'UKR', website: 'https://woodmood.com.ua' },
  { name: 'Climate Café',                                cat: C('Climat'),              rawCat: 'Climate Engagement',            country: 'United Kingdom',     iso: 'GBR', website: 'https://www.climatecafe.earth' },
  { name: 'Climate Savers',                              cat: C('Climat'),              rawCat: 'Climate App / Rewards',         country: 'United Kingdom',     iso: 'GBR', website: 'https://www.climatesavers.io' },
  { name: 'Flexi-Hex',                                   cat: C('Économie circulaire'), rawCat: 'Circularity',                   country: 'United Kingdom',     iso: 'GBR', website: 'https://flexi-hex.com' },
  { name: 'HALO Trust',                                  cat: C('Inclusion'),           rawCat: 'Post-conflict land restoration', country: 'United Kingdom',    iso: 'GBR', website: 'https://www.halotrust.org' },
  { name: 'Notpla',                                      cat: C('Matériaux'),           rawCat: 'Circular Materials',            country: 'United Kingdom',     iso: 'GBR', website: 'https://www.notpla.com' },
  { name: 'Project Seagrass',                            cat: C('Océans'),              rawCat: 'Ocean / Biodiversity',          country: 'United Kingdom',     iso: 'GBR', website: 'https://www.projectseagrass.org' },
  { name: 'SED Fund',                                    cat: C("Finance d'impact"),    rawCat: 'Climate Philanthropy',          country: 'United Kingdom',     iso: 'GBR', website: 'https://www.sed.fund' },
  { name: 'Save Your Wardrobe',                          cat: C('Économie circulaire'), rawCat: 'Circular Fashion',              country: 'United Kingdom',     iso: 'GBR', website: 'https://saveyourwardrobe.com' },
  { name: 'Sparxell',                                    cat: C('Matériaux'),           rawCat: 'Materials',                     country: 'United Kingdom',     iso: 'GBR', website: 'https://www.sparxell.com' },
  { name: 'TETMET',                                      cat: C('Matériaux'),           rawCat: 'Materials',                     country: 'United Kingdom',     iso: 'GBR', website: 'https://tetmet.com' },
  { name: 'explorer.land',                               cat: C('Biodiversité'),        rawCat: 'Nature Finance / Restoration',  country: 'United Kingdom',     iso: 'GBR', website: 'https://explorer.land' },
  { name: 'Arbimon',                                     cat: C('Biodiversité'),        rawCat: 'Biodiversity / Bioacoustics',   country: 'United States',     iso: 'USA', website: 'https://arbimon.rfcx.org' },
  { name: 'Brightest',                                   cat: C('Climat'),              rawCat: 'ESG / Climate Software',        country: 'United States',     iso: 'USA', website: 'https://www.brightest.io' },
  { name: 'Humanitarian OpenStreetMap Team',             cat: C('Inclusion'),           rawCat: 'Inclusion / Mapping',           country: 'United States',     iso: 'USA', website: 'https://www.hotosm.org' },
  { name: 'Loop',                                        cat: C('Économie circulaire'), rawCat: 'Circular Reuse',                country: 'United States',     iso: 'USA', website: 'https://www.loopstore.com' },
  { name: 'Mycocycle',                                   cat: C('Économie circulaire'), rawCat: 'Circularity / Materials',       country: 'United States',     iso: 'USA', website: 'https://mycocycle.com/' },
  { name: 'Preservaland',                                cat: C('Biodiversité'),        rawCat: 'Biodiversity',                  country: 'United States',     iso: 'USA', website: 'https://preserva.land/index.php/en/' },
  { name: 'Rainforest Connection',                       cat: C('Biodiversité'),        rawCat: 'Biodiversity / Monitoring',     country: 'United States',     iso: 'USA', website: 'https://rfcx.org' },
  { name: 'Snova',                                       cat: C('Sciences & Tech'),     rawCat: 'Bioinnovation',                 country: 'United States',     iso: 'USA', website: 'https://www.snova.bio' },
  { name: 'Werewool',                                    cat: C('Matériaux'),           rawCat: 'Materials',                     country: 'United States',     iso: 'USA', website: 'https://www.werewool.bio' },
  { name: 'World Resources Institute',                   cat: C('Climat'),              rawCat: 'Climate / Data / Policy',       country: 'United States',     iso: 'USA', website: 'https://www.wri.org' },
  { name: 're:3D',                                       cat: C('Économie circulaire'), rawCat: 'Circularity / Manufacturing',   country: 'United States',     iso: 'USA', website: 'https://re3d.org' },
]
